language: java

addons:
  sonarcloud:
    organization: "amarteleto-github"
    token:
      secure: "1f9cc5e30a44454e8c31c53537d067d54db0f7d6"
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

deploy:
  provider: heroku
  api_key:
    secure: "bece5235-be66-4621-a63b-86052995fd09"
  app: kumuluzee-locadora-cliente
